spring:
  application:
    name: hhplus

  profiles:
    active: local

  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: DLtmdals0106!!!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000

  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC


springdoc:
  swagger-ui:
    path: /swagger-ui.html
